from __future__ import annotations


def source_record() -> dict[str, object]:
    return {
        "source_id": "example-cliffside-official",
        "venue_id": "example-cliffside-resort",
        "source_type": "official",
        "source_name": "Example Cliffside Weddings",
        "source_url": "https://example.com/cliffside/weddings",
        "captured_at": "2026-06-18",
        "content_date_if_known": "2026-05-01",
        "language": "en",
        "evidence_categories": ["pricing", "photos", "restrictions", "accommodation"],
        "reliability_notes": "Synthetic official source for test coverage",
        "raw_excerpt_summary": "Contains pricing, image gallery, and venue constraints",
    }


def photo_records() -> list[dict[str, object]]:
    return [
        {
            "photo_entry_id": "example-photo-1",
            "venue_id": "example-cliffside-resort",
            "source_id": "example-cliffside-official",
            "page_url": "https://example.com/cliffside/gallery/1",
            "image_url_or_gallery_url": "https://example.com/images/1.jpg",
            "image_type": "real_wedding_feature",
            "scene_tags": ["cliffside-ceremony", "guest-seating"],
            "authenticity": "real_wedding",
            "coverage_type": "large_gallery",
            "decision_value": "high",
            "decision_notes": "Shows full ceremony setup and aisle width",
        },
        {
            "photo_entry_id": "example-photo-2",
            "venue_id": "example-cliffside-resort",
            "source_id": "example-cliffside-official",
            "page_url": "https://example.com/cliffside/gallery/2",
            "image_url_or_gallery_url": "https://example.com/images/2.jpg",
            "image_type": "real_wedding_feature",
            "scene_tags": ["cliffside-ceremony", "night-view"],
            "authenticity": "real_wedding",
            "coverage_type": "large_gallery",
            "decision_value": "high",
            "decision_notes": "Shows dinner seating layout and lighting",
        },
        {
            "photo_entry_id": "example-photo-3",
            "venue_id": "example-cliffside-resort",
            "source_id": "example-cliffside-official",
            "page_url": "https://example.com/cliffside/gallery/3",
            "image_url_or_gallery_url": "https://example.com/images/3.jpg",
            "image_type": "official_hotel_gallery",
            "scene_tags": ["room"],
            "authenticity": "official_promotional",
            "coverage_type": "small_gallery",
            "decision_value": "low",
            "decision_notes": "Single room photo",
        },
    ]


def venue_record() -> dict[str, object]:
    return {
        "id": "example-cliffside-resort",
        "name_zh": "範例懸崖度假村",
        "name_en_official": "Example Cliffside Resort",
        "brand_or_group": "Example Hospitality",
        "venue_operator_type": "resort",
        "is_standalone": False,
        "region": "Uluwatu",
        "subarea": "Southern Ridge",
        "official_website": "https://example.com/cliffside",
        "maps_url": "https://maps.example.com/cliffside",
        "address_text": "Uluwatu, Bali",
        "venue_types": ["cliffside", "chapel"],
        "primary_visual_identity": "Oceanfront cliffside ceremony deck",
        "ceremony_space_types": ["chapel", "cliffside-terrace"],
        "reception_space_types": ["garden", "private-dining"],
        "supports_ceremony_only": True,
        "supports_ceremony_and_dinner": True,
        "supports_buyout": False,
        "supports_micro_wedding": True,
        "guest_capacity_ceremony_min": 10,
        "guest_capacity_ceremony_max": 60,
        "guest_capacity_dinner_min": 20,
        "guest_capacity_dinner_max": 90,
        "recommended_guest_size_band": "81-120",
        "pricing_status": "public_price_available",
        "price_entries": [
            {
                "label": "Cliffside ceremony package",
                "currency": "USD",
                "amount_min": 8500,
                "amount_max": None,
                "pricing_year": 2026,
                "includes_stay": False,
                "includes_decoration": True,
                "includes_dinner": False,
                "includes_tax_service": False,
                "conditions_text": "Ceremony package only",
                "confidence": "high",
            }
        ],
        "price_summary_text": "Public ceremony package starts at USD 8,500",
        "price_risk_level": "low",
        "rain_backup_status": "strong",
        "has_indoor_backup": True,
        "has_covered_backup": True,
        "backup_space_description": "Indoor lounge backup",
        "backup_quality_notes": "Backup maintains sea-facing access",
        "weather_exposure_notes": "Primary deck is wind exposed",
        "airport_drive_time_minutes_estimate": 40,
        "transport_notes": "Traffic slows near sunset hours",
        "traffic_risk_level": "high",
        "onsite_accommodation_available": True,
        "onsite_room_inventory_notes": "Enough rooms for immediate family groups",
        "nearby_accommodation_notes": "Additional cliffside stays require shuttles",
        "accommodation_fit": "workable_with_shuttles",
        "guest_mobility_notes": "Best with arranged transfers for older guests",
        "restriction_level": "medium",
        "noise_cutoff_notes": "Outdoor amplified music ends at 22:00",
        "external_vendor_policy": "External vendors allowed with prior approval",
        "minimum_stay_requirement_notes": "No mandatory buyout",
        "minimum_spend_notes": "Reception minimum spend applies",
        "drone_policy_notes": "Drone use requires venue approval",
        "family_child_notes": "Children allowed with supervision",
        "religious_or_space_use_notes": "Symbolic ceremony focus",
        "operational_constraints_notes": "Popular sunset block fills early",
        "style_tags": ["cliffside", "ocean-view", "chapel"],
        "price_band_normalized": None,
        "best_for": ["Couples prioritizing dramatic cliffside visuals"],
        "not_ideal_for": ["Guests seeking the shortest airport transfer"],
        "key_strengths": ["Strong scenery", "Clear ceremony imagery"],
        "key_risks": ["High traffic risk", "Reception minimum spend"],
        "data_completeness": "deep_complete",
        "research_status": "deep_research_complete",
        "last_verified_at": "2026-06-18",
        "data_freshness": "recent",
        "open_questions": ["Confirm corkage fees for external alcohol"],
        "source_ids": ["example-cliffside-official"],
        "photo_index_id": "example-cliffside-resort",
    }
